<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Funcs" Id="{ee771c61-4cc8-49fe-a213-1138bcc939e9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Funcs
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Funcs">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>