<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{da1e2e68-f202-4ed0-8d51-9abdfc0ccaa5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[UpdateHigh();
UpdateTemp();
UpdateConc();
SetCIP(FALSE);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="16" Count="1" />
      <LineId Id="7" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>