<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="VolNow" Id="{77c24618-b925-4840-a558-accae81d177a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION VolNow : REAL]]></Declaration>
    <Implementation>
      <ST><![CDATA[VolNow := GVL.tank_area * GVL.high_now;]]></ST>
    </Implementation>
    <LineIds Name="VolNow">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>